@startuml StateMachineDiagram
state "Ресурс" as Resource {
    [*] --> Resource.Доступно : Инициализация / Деактивация
    state Доступно {
        Доступно --> Забронировано : Пользователь бронирует
        Доступно --> Недоступно : Администратор блокирует / Отказ оборудования
        Доступно --> ТехРаботы : Администратор переводит в тех. работы
    }

    state Забронировано {
        Забронировано --> Используется : Наступление времени бронирования (автоматически)
        Забронировано --> Доступно : Отмена бронирования (пользователем/администратором)
        Забронировано --> Недоступно : Отказ оборудования (во время бронирования)
    }

    state Используется {
        Используется --> Доступно : Окончание времени бронирования (автоматически) / Деактивация
        Используется --> Недоступно : Отказ оборудования (во время использования)
    }

    state Недоступно {
        Недоступно --> Доступно : Устранение неисправности / Администратор разблокирует
    }

    state "Тех. работы" as ТехРаботы {
        ТехРаботы --> Доступно : Администратор завершает тех. работы
    }
}


@enduml